opcodes = {
    "NOOP": "000000",
    "JE": "000001",
    "JNE": "000010",
    "JL": "000011",
    "JG": "000100",
    "JGE": "000101",
    "JLE": "000110",
    "MOV": "000111",
    "LDS": "001000",
    "LDU": "001001",
    "LDW": "001010",
    "LDI": "001011",
    "STOREW": "001100",
    "STOREB": "001101",
    "JUMP": "001110",
    "ADD": "001111",
    "SUB": "010000",
    "AND": "010001",
    "OR": "010010",
    "XOR": "010011",
    "SHL": "010100",
    "SHR": "010101",
    "SAR": "010110",
    "ROL": "010111",
    "ROR": "011000",
    "NEG": "011001",
    "MUL": "011010",
    "IMUL": "011011",
    "DIV": "011100",
    "IDIV": "011101",
    "SWDS": "011110",
    "SWCS": "011111",
    "RLDS": "100000",
    "RLDU": "100001",
    "RLDW": "100010",
    "RSTOREW": "100011",
    "RSTOREB": "100100",
    "ISET": "100101",
    "ICLR": "100110",
    "IRET": "100111",
}

TYPE_REG = 1
TYPE_IMM = 2
TYPE_MEM = 3
TYPE_PAD = 4

operations_dict = {
    # No operands
    "NOOP": [TYPE_PAD],
    # Conditional Jumps
    "JE": [TYPE_REG, TYPE_REG, TYPE_MEM],
    "JNE": [TYPE_REG, TYPE_REG, TYPE_MEM],
    "JL": [TYPE_REG, TYPE_REG, TYPE_MEM],
    "JG": [TYPE_REG, TYPE_REG, TYPE_MEM],
    "JGE": [TYPE_REG, TYPE_REG, TYPE_MEM],
    "JLE": [TYPE_REG, TYPE_REG, TYPE_MEM],
    # Data Transfer
    "MOV": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "LDS": [TYPE_REG, TYPE_PAD, TYPE_MEM],
    "LDU": [TYPE_REG, TYPE_PAD, TYPE_MEM],
    "LDW": [TYPE_REG, TYPE_PAD, TYPE_MEM],
    "LDI": [TYPE_REG, TYPE_PAD, TYPE_IMM],
    "STOREW": [TYPE_REG, TYPE_PAD, TYPE_MEM],
    "STOREB": [TYPE_REG, TYPE_PAD, TYPE_MEM],
    # Unconditional Jump
    "JUMP": [TYPE_REG, TYPE_PAD],
    # Arithmetic & Logic
    "ADD": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "SUB": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "AND": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "OR": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "XOR": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "SHL": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "SHR": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "SAR": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "ROL": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "ROR": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "NEG": [TYPE_REG, TYPE_REG, TYPE_PAD],
    # Multiplication
    "MUL": [TYPE_REG, TYPE_REG, TYPE_REG, TYPE_PAD],
    "IMUL": [TYPE_REG, TYPE_REG, TYPE_REG, TYPE_PAD],
    # Division
    "DIV": [TYPE_REG, TYPE_REG, TYPE_REG, TYPE_PAD],
    "IDIV": [TYPE_REG, TYPE_REG, TYPE_REG, TYPE_PAD],
    # Register memory addressing
    "RLDS": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "RLDU": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "RLDW": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "RSTOREW": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "RSTOREB": [TYPE_REG, TYPE_REG, TYPE_PAD],
    "ISET": [TYPE_PAD],
    "ICLR": [TYPE_PAD],
    "IRET": [TYPE_PAD],
    "SWDS": [TYPE_REG, TYPE_PAD],
    "SWCS": [TYPE_REG, TYPE_PAD],
}
